import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Esqueleton',
  description: 'Generated by esqueleton-project',
}

// Layout raiz — apenas a estrutura básica da página.
// O cabeçalho e os contextos do site público vivem em /loja/[slug]/layout.tsx
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body>{children}</body>
    </html>
  )
}
