import type { Metadata } from 'next'
import { BagProvider } from '@/contexts/bag-context'
import { StoreProfileProvider } from '@/contexts/store-profile-context'
import { CustomerProvider } from '@/contexts/customer-context'
import { HeaderWithProfile } from '@/components/header/HeaderWithProfile'
import { AnnouncementBar } from '@/components/header/AnnouncementBar'
import './globals.css'

export const metadata: Metadata = {
  title: 'Esqueleton',
  description: 'Generated by esqueleton-project',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body>
        <StoreProfileProvider>
          <CustomerProvider>
            <BagProvider>
              <AnnouncementBar />
              <HeaderWithProfile />
              {children}
            </BagProvider>
          </CustomerProvider>
        </StoreProfileProvider>
      </body>
    </html>
  )
}
