export { ProductCard } from './components/ProductCard'
export { ProductPrice } from './components/ProductPrice'
export { CatalogSearch } from './components/CatalogSearch'
export { CatalogFilters } from './components/CatalogFilters'
export { DisplayToggle } from './components/DisplayToggle'
export { catalogService } from './services/catalog.service'
export type { ProductsPage, ProductsQuery } from './services/catalog.service'
export { compressImage } from './utils/image'
