export { ProductCard } from './components/ProductCard'
export { ProductPrice } from './components/ProductPrice'
export { CatalogSearch } from './components/CatalogSearch'
export { CatalogSearchCompact } from './components/CatalogSearchCompact'
export { CatalogFilters } from './components/CatalogFilters'
export { DisplayToggle } from './components/DisplayToggle'
export { CatalogWidget } from './components/CatalogWidget'
export type { CatalogWidgetData } from './components/CatalogWidget'
export { catalogService } from './services/catalog.service'
export type { ProductsPage, ProductsQuery } from './services/catalog.service'
export { compressImage } from './utils/image'
export { resolveCatalogLayout, findLayoutItem, defaultPositionForType, DEFAULT_LAYOUT_ITEMS } from './utils/catalog-layout'
