export { ProductCard } from './components/ProductCard'
export { ProductPrice } from './components/ProductPrice'
export { ProductSuggestions } from './components/ProductSuggestions'
export { CatalogSearch } from './components/CatalogSearch'
export { CatalogFilters } from './components/CatalogFilters'
export { DisplayToggle } from './components/DisplayToggle'
export { catalogService } from './services/catalog.service'
export type { ProductsPage, ProductsQuery } from './services/catalog.service'
export { VariantPickerModal } from './components/VariantPickerModal'
export { ImageUploader } from './components/ImageUploader'
export { VariantsEditor } from './components/VariantsEditor'
export { compressImage } from './utils/image'
export { getOptionGroups, findVariant } from './utils/variants'
